baseURL: "https://jota.one/"
languageCode: "en-us"
title: "Jota"
theme: ["jota-shortcodes", "jota-corp"]
markup:
  goldmark:
    renderer:
      unsafe: true
params:
  description: We build web products
  og:
    image: /img/og.png
  jota:
    config:
      contentMaxWidth: "1400px"
menu:
  main:
    - name: Meat
      identifier: meat
      weight: 100
      url: "/#meat"
    - name: Products
      identifier: products
      weight: 200
      url: "/#products"
    - name: Projects
      identifier: projects
      weight: 200
      url: "/#projects"
    - name: About
      identifier: about
      weight: 400
      url: "/#about"