# The URL the site will be built for
base_url = "https://jota.one"
title = "Jota"
description = "We build web products"
default_language = "en"
minify_html = false # Breaks code block rendering in templates when active...
build_search_index = true

[markdown]
highlight_code = true
highlight_theme = "two-dark"
render_emoji = true
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
[[extra.social]]
url = "https://github.com/jota-one"
icon = "github"

[[extra.social]]
url = "https://www.npmjs.com/org/jota-one"
icon = "npm"

[[extra.social]]
url = "https://linkedin.com/jota-one"
icon = "linkedin"

[[extra.social]]
url = "https://twitter.com/jota-one"
icon = "twitter"
